apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  ports:
    - name: scrape
      port: 8443
      targetPort: 8443
      nodePort: 32500
      protocol: TCP
  selector:
    app: web-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: web-service
  template:
    metadata:
      labels:
        app: web-service
      name: web-service
    spec:
      containers:
      - image: ketidevit/test-commit:v1
        name: web-service
        ports:
        - containerPort: 8490
          hostPort: 8443
          name: scrape
      nodeName: hcp-worker2

