apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 10.0.5.94-10.0.5.96
  autoAssign: true
#  - 192.168.9.1-192.168.9.5
#  - fc00:f853:0ccd:e799::/124
