apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    volumeMounts:
    - name: hostpath-vol
      mountPath: /hostpath
    - name: emptydir-vol
      mountPath: /emptydir
  volumes:
  - name: emptydir-vol
    emptyDir: {}
  - name: hostpath-vol
    hostPath:
      path: /tmp/hostpath
      type: DirectoryOrCreate