apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-mainui
  annotations:
    kubernetes.io/change-cause: httpd:2.4
  labels:
    name: apache
    app: main
    rel: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      name: apache
      app: main
      rel: stable  
  template:
    metadata:
      name: pod-mainui
      labels:
        name: apache
        app: main
        rel: stable       
    spec:
      containers:
      - name: container
        image: httpd:2.4