apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14
    volumeMounts:
    - mountPath: /mount1
      name: emptydir-vol
    ports:
    - containerPort: 80
  # - name: centos-container
  #   image: centos:7
  #   volumeMounts:
  #   - mountPath: /mount2
  #     name: emptydir-vol
  volumes: 
  - name: emptydir-vol 
    emptyDir: {}