apiVersion: v1
kind: Pod
metadata:
  name: pod-liveness
spec:
  containers:
  - name: unhealthy
    image: smlinux/unhealthy
    livenessProbe:
      httpGet:
        path: /
        port: 80
      failureThreshold: 2
      initialDelaySeconds: 10
      periodSeconds: 20
  
