apiVersion: v1
kind: Pod
metadata: 
  name: busybox
spec: 
  containers:
  - name: busybox-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 50; rm -rf /tmp/healthy; sleep 30;
    livenessProbe:
      exec:
        command:      
        - ls
        - /tmp/healthy
      periodSeconds: 10
      initialDelaySeconds: 10
      successThreshold: 1
      failureThreshold: 2
