apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu
spec:
  containers:
    - name: tensorflow-container
      image: tensorflow/tensorflow:nightly-jupyter
      ports:
      - protocol: TCP
        containerPort: 8888
  nodeSelector:
    gpu: "true" 
