apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources: 
    requests:
     storage: 2Gi
  storageClassName: manual
